--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

-- Started on 2025-05-09 02:48:28

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 66547)
-- Name: mst_config; Type: TABLE; Schema: public; Owner: admin_db
--

CREATE TABLE public.mst_config (
    id integer NOT NULL,
    config_key character varying(500) NOT NULL,
    config_value text,
    is_active boolean DEFAULT true,
    created_by integer DEFAULT '-1'::integer NOT NULL,
    created_at time without time zone DEFAULT now(),
    last_modified_by integer DEFAULT '-1'::integer NOT NULL,
    last_modified_at time without time zone DEFAULT now()
);


ALTER TABLE public.mst_config OWNER TO admin_db;

--
-- TOC entry 215 (class 1259 OID 66546)
-- Name: mst_config_id_seq; Type: SEQUENCE; Schema: public; Owner: admin_db
--

ALTER TABLE public.mst_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mst_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 9999999
    CACHE 1
    CYCLE
);


--
-- TOC entry 221 (class 1259 OID 66595)
-- Name: mst_product; Type: TABLE; Schema: public; Owner: admin_db
--

CREATE TABLE public.mst_product (
    id integer NOT NULL,
    name character varying(500) NOT NULL,
    description text,
    price money DEFAULT 0 NOT NULL,
    is_active boolean DEFAULT true,
    created_by integer DEFAULT '-1'::integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    last_modified_by integer DEFAULT '-1'::integer NOT NULL,
    last_modified_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.mst_product OWNER TO admin_db;

--
-- TOC entry 218 (class 1259 OID 66560)
-- Name: mst_user; Type: TABLE; Schema: public; Owner: admin_db
--

CREATE TABLE public.mst_user (
    id integer NOT NULL,
    username character varying(50) NOT NULL,
    full_name character varying(100) NOT NULL,
    email character varying(50) NOT NULL,
    phone character varying(14) NOT NULL,
    password_hash text NOT NULL,
    is_active boolean DEFAULT true,
    created_by integer DEFAULT '-1'::integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    last_modified_by integer DEFAULT '-1'::integer NOT NULL,
    last_modified_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.mst_user OWNER TO admin_db;

--
-- TOC entry 217 (class 1259 OID 66559)
-- Name: mst_user_id_seq; Type: SEQUENCE; Schema: public; Owner: admin_db
--

ALTER TABLE public.mst_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mst_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 9999999
    CACHE 1
    CYCLE
);


--
-- TOC entry 220 (class 1259 OID 66594)
-- Name: mst_wallet_id_seq; Type: SEQUENCE; Schema: public; Owner: admin_db
--

ALTER TABLE public.mst_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mst_wallet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 9999999
    CACHE 1
    CYCLE
);


--
-- TOC entry 219 (class 1259 OID 66584)
-- Name: tbl_log_transac; Type: TABLE; Schema: public; Owner: admin_db
--

CREATE TABLE public.tbl_log_transac (
    log_transac_id uuid DEFAULT gen_random_uuid() NOT NULL,
    transac_type character varying(200) NOT NULL,
    transac_id integer NOT NULL,
    transac_step integer NOT NULL,
    transac_action character varying(200) NOT NULL,
    transac_by integer NOT NULL,
    transac_start_at timestamp without time zone DEFAULT now() NOT NULL,
    transac_finish_at timestamp without time zone,
    transac_params text,
    transac_next text,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.tbl_log_transac OWNER TO admin_db;

--
-- TOC entry 4875 (class 0 OID 66547)
-- Dependencies: 216
-- Data for Name: mst_config; Type: TABLE DATA; Schema: public; Owner: admin_db
--

COPY public.mst_config (id, config_key, config_value, is_active, created_by, created_at, last_modified_by, last_modified_at) FROM stdin;
\.


--
-- TOC entry 4880 (class 0 OID 66595)
-- Dependencies: 221
-- Data for Name: mst_product; Type: TABLE DATA; Schema: public; Owner: admin_db
--

COPY public.mst_product (id, name, description, price, is_active, created_by, created_at, last_modified_by, last_modified_at) FROM stdin;
1	Donat Gula Gula	Donat tradisional dengan taburan gula halus	$4,500.00	t	1	2025-05-09 00:27:38.561855	1	2025-05-09 00:30:38.223375
\.


--
-- TOC entry 4877 (class 0 OID 66560)
-- Dependencies: 218
-- Data for Name: mst_user; Type: TABLE DATA; Schema: public; Owner: admin_db
--

COPY public.mst_user (id, username, full_name, email, phone, password_hash, is_active, created_by, created_at, last_modified_by, last_modified_at) FROM stdin;
1	admin1	Admin ke 1	admin1@gmail.com	0812102663005	498CB4BE8335C7FCB3DD67048955F22B3B48D61C4D0FECF9DADA52780AC0840E:9BBB514BB107018314DCFD3CD2DD2E66:50000:SHA256	t	-1	2025-05-09 00:26:19.159092	-1	2025-05-09 00:26:19.159185
\.


--
-- TOC entry 4878 (class 0 OID 66584)
-- Dependencies: 219
-- Data for Name: tbl_log_transac; Type: TABLE DATA; Schema: public; Owner: admin_db
--

COPY public.tbl_log_transac (log_transac_id, transac_type, transac_id, transac_step, transac_action, transac_by, transac_start_at, transac_finish_at, transac_params, transac_next, created_at) FROM stdin;
\.


--
-- TOC entry 4886 (class 0 OID 0)
-- Dependencies: 215
-- Name: mst_config_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin_db
--

SELECT pg_catalog.setval('public.mst_config_id_seq', 1, false);


--
-- TOC entry 4887 (class 0 OID 0)
-- Dependencies: 217
-- Name: mst_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin_db
--

SELECT pg_catalog.setval('public.mst_user_id_seq', 1, true);


--
-- TOC entry 4888 (class 0 OID 0)
-- Dependencies: 220
-- Name: mst_wallet_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin_db
--

SELECT pg_catalog.setval('public.mst_wallet_id_seq', 1, true);


--
-- TOC entry 4722 (class 2606 OID 66558)
-- Name: mst_config mst_config_pkey; Type: CONSTRAINT; Schema: public; Owner: admin_db
--

ALTER TABLE ONLY public.mst_config
    ADD CONSTRAINT mst_config_pkey PRIMARY KEY (id);


--
-- TOC entry 4724 (class 2606 OID 66571)
-- Name: mst_user mst_user_pkey; Type: CONSTRAINT; Schema: public; Owner: admin_db
--

ALTER TABLE ONLY public.mst_user
    ADD CONSTRAINT mst_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4730 (class 2606 OID 66607)
-- Name: mst_product mst_wallet_pkey; Type: CONSTRAINT; Schema: public; Owner: admin_db
--

ALTER TABLE ONLY public.mst_product
    ADD CONSTRAINT mst_wallet_pkey PRIMARY KEY (id);


--
-- TOC entry 4728 (class 2606 OID 66593)
-- Name: tbl_log_transac tbl_log_pkey; Type: CONSTRAINT; Schema: public; Owner: admin_db
--

ALTER TABLE ONLY public.tbl_log_transac
    ADD CONSTRAINT tbl_log_pkey PRIMARY KEY (log_transac_id);


--
-- TOC entry 4726 (class 2606 OID 66573)
-- Name: mst_user unique; Type: CONSTRAINT; Schema: public; Owner: admin_db
--

ALTER TABLE ONLY public.mst_user
    ADD CONSTRAINT "unique" UNIQUE (email, phone);


-- Completed on 2025-05-09 02:48:28

--
-- PostgreSQL database dump complete
--

